# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test & Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  # Test job
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
          npm run build --if-present
          npm run test:unit
          npm run test:e2e

  # Deployment job
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'Mekyi'
          reponame: 'song-contest-rating'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
